/**
 * Component documentation registry for TechSkillPlanet React Web controls.
 * Used by the sample app (BasicControlsSample) to render an interactive catalog.
 */

/** Component category groups in display order. */
export const componentCategories = [
  'Actions',
  'Surfaces',
  'Feedback',
  'Inputs',
  'Navigation',
  'Data'
];

/** Full component documentation entries. */
export const componentDocs = [
  // Actions
  { name: 'Button', component: 'TspButton', category: 'Actions', description: 'Primary action button with primary, default, danger, text and link variants.', props: ['text', 'variant', 'disabled', 'fullWidth', 'theme', 'onTap'], variants: ['primary', 'default', 'danger', 'text'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },
  { name: 'Chip', component: 'TspChip', category: 'Actions', description: 'Selectable tag for filtering and lightweight actions.', props: ['text', 'variant', 'selected', 'disabled', 'theme', 'onTap'], variants: ['default'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },
  { name: 'IconButton', component: 'TspIconButton', category: 'Actions', description: 'Icon-based button for toolbars and quick actions.', props: ['icon', 'selected', 'disabled', 'variant', 'theme', 'onTap'], variants: ['default', 'primary'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },
  { name: 'TextLink', component: 'TspTextLink', category: 'Actions', description: 'Text link button for secondary navigation.', props: ['text', 'inverse', 'theme', 'onTap'], variants: ['default', 'inverse'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },

  // Surfaces
  { name: 'Card', component: 'TspCard', category: 'Surfaces', description: 'Content container for grouped content with optional selection.', props: ['variant', 'selected', 'disabled', 'theme', 'children'], variants: ['default'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },
  { name: 'ListItem', component: 'TspListItem', category: 'Surfaces', description: 'List row with title, message, trailing element and states.', props: ['title', 'message', 'trailing', 'selected', 'disabled', 'theme', 'onTap'], variants: ['default'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },
  { name: 'Empty', component: 'TspEmpty', category: 'Surfaces', description: 'Empty state placeholder with illustration, title and action.', props: ['title', 'message', 'actionText', 'theme', 'onAction'], variants: ['default'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },
  { name: 'RefreshLayout', component: 'TspRefreshLayout', category: 'Surfaces', description: 'Pull-to-refresh and load-more scroll host for lists.', props: ['refreshing', 'loadingMore', 'disabled', 'theme', 'onRefresh', 'onLoadMore', 'children'], variants: ['default'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },

  // Feedback
  { name: 'Alert', component: 'TspAlert', category: 'Feedback', description: 'Inline alert for success, warning, error and info messages.', props: ['title', 'message', 'variant', 'theme'], variants: ['info', 'success', 'warning', 'error'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },
  { name: 'Badge', component: 'TspBadge', category: 'Feedback', description: 'Short text status badge for counts and labels.', props: ['text', 'variant', 'disabled', 'theme'], variants: ['default', 'primary', 'success', 'warning', 'danger'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },
  { name: 'Progress', component: 'TspProgress', category: 'Feedback', description: 'Progress bar with semantic color variants.', props: ['progress', 'variant', 'theme'], variants: ['primary', 'success', 'warning', 'danger'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },
  { name: 'Notification', component: 'TspNotification', category: 'Feedback', description: 'Notification card for task reminders and status alerts.', props: ['title', 'message', 'variant', 'theme'], variants: ['info', 'alert'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },
  { name: 'Toast', component: 'TspToast', category: 'Feedback', description: 'Temporary toast notification for brief feedback.', props: ['message', 'variant', 'duration', 'theme'], variants: ['info', 'success', 'warning', 'error'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },
  { name: 'Modal', component: 'TspModal', category: 'Feedback', description: 'Confirmation dialog with confirm and cancel actions.', props: ['title', 'message', 'confirmText', 'cancelText', 'theme', 'onConfirm', 'onCancel'], variants: ['default'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },
  { name: 'LoadingDialog', component: 'TspLoadingDialog', category: 'Feedback', description: 'Blocking loading overlay for submit and sync waits.', props: ['visible', 'message', 'variant', 'dismissible', 'theme', 'onDismiss'], variants: ['default', 'compact'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },

  // Inputs
  { name: 'Input', component: 'TspInput', category: 'Inputs', description: 'Single-line text input with error and disabled states.', props: ['value', 'placeholder', 'variant', 'disabled', 'theme', 'onChange'], variants: ['default', 'error'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },
  { name: 'Select', component: 'TspSelect', category: 'Inputs', description: 'Select trigger that opens a bottom OptionSheet.', props: ['options', 'selectedIndex', 'disabled', 'theme', 'onSelect'], variants: ['default'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },
  { name: 'OptionSheet', component: 'TspOptionSheet', category: 'Inputs', description: 'Bottom sheet option picker for mobile-style selection.', props: ['title', 'options', 'selectedIndex', 'visible', 'theme', 'onSelect', 'onCancel'], variants: ['default'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },
  { name: 'Switch', component: 'TspSwitch', category: 'Inputs', description: 'Toggle switch with loading and disabled states.', props: ['text', 'checked', 'checkedText', 'uncheckedText', 'loading', 'disabled', 'theme', 'onChange'], variants: ['default'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },
  { name: 'Checkbox', component: 'TspCheckbox', category: 'Inputs', description: 'Checkbox with brand checkmark box and label.', props: ['text', 'variant', 'checked', 'disabled', 'theme', 'onChange'], variants: ['default', 'disabled'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'Radio', component: 'TspRadio', category: 'Inputs', description: 'Single radio option; group exclusivity is app-owned.', props: ['text', 'checked', 'disabled', 'theme', 'onChange'], variants: ['default', 'disabled'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'Collapse', component: 'TspCollapse', category: 'Surfaces', description: 'Expandable accordion panel.', props: ['title', 'message', 'expanded', 'disabled', 'theme', 'onChange'], variants: ['default', 'disabled'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'Divider', component: 'TspDivider', category: 'Surfaces', description: 'Horizontal hairline divider.', props: ['variant', 'text', 'disabled', 'theme'], variants: ['default', 'disabled'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'SearchBar', component: 'TspSearchBar', category: 'Inputs', description: 'Pill search field.', props: ['value', 'placeholder', 'variant', 'disabled', 'theme', 'onChange'], variants: ['default', 'disabled'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'SegmentedControl', component: 'TspSegmentedControl', category: 'Navigation', description: 'Equal-width segmented control.', props: ['options', 'selectedIndex', 'disabled', 'theme', 'onSelect'], variants: ['default', 'disabled'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'StarRating', component: 'TspStarRating', category: 'Inputs', description: 'Interactive star rating with readonly and disabled variants.', props: ['value', 'max', 'disabled', 'variant', 'theme', 'onChange'], variants: ['default', 'disabled', 'readonly'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'PinInput', component: 'TspPinInput', category: 'Inputs', description: 'PIN/verification code input with secure mode.', props: ['value', 'cellCount', 'secure', 'theme', 'onChange', 'onComplete'], variants: ['default'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },

  // Navigation
  { name: 'TopBar', component: 'TspTopBar', category: 'Navigation', description: 'Top navigation bar with title and optional back button.', props: ['title', 'showBack', 'backgroundColor', 'theme', 'onBack'], variants: ['default'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },
  { name: 'BottomTab', component: 'TspBottomTab', category: 'Navigation', description: 'Primary page bottom tab bar for 3-5 entries.', props: ['tabs', 'selectedKey', 'theme', 'onSelect'], variants: ['default'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },
  { name: 'Tabs', component: 'TspTabs', category: 'Navigation', description: 'In-page segmented tabs for content filtering.', props: ['tabs', 'selectedIndex', 'theme', 'onSelect'], variants: ['default'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },
  { name: 'StickyFooter', component: 'TspStickyFooter', category: 'Navigation', description: 'Fixed bottom action area for primary page actions.', props: ['content', 'theme', 'children'], variants: ['default'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },

  // Data
  { name: 'Amount', component: 'TspAmount', category: 'Data', description: 'Monetary/numeric display with currency symbol and cycle.', props: ['symbol', 'value', 'cycle', 'symbolAfter', 'strikeThrough', 'theme'], variants: ['default'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },
  { name: 'KeyValueLabel', component: 'TspKeyValueLabel', category: 'Data', description: 'Key-value pair display for summary information.', props: ['label', 'value', 'theme'], variants: ['default'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },
  { name: 'Stepper', component: 'TspStepper', category: 'Data', description: 'Step progress indicator for 3-5 steps.', props: ['stepCount', 'currentStep', 'theme'], variants: ['default'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View'] },
  { name: 'DatePicker', component: 'TspDatePicker', category: 'Inputs', description: 'Themed YYYY-MM-DD date field.', props: ['value', 'min', 'max', 'placeholder', 'disabled', 'theme', 'onChange'], variants: ['default', 'disabled'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'ChildSwitcher', component: 'TspChildSwitcher', category: 'Navigation', description: 'Single-select child switcher in chip or tabs variant.', props: ['items', 'selectedId', 'variant', 'disabled', 'theme', 'onChange'], variants: ['chip', 'tabs'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'ScoreRuleGrid', component: 'TspScoreRuleGrid', category: 'Data', description: 'Score rule cards with optional +1 increment and responsive columns.', props: ['rules', 'columns', 'variant', 'disabled', 'theme', 'onIncrement'], variants: ['default', 'readOnly'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'RedeemCardGrid', component: 'TspRedeemCardGrid', category: 'Data', description: 'Preset redeem item cards with frozen/insufficient states.', props: ['items', 'availablePoints', 'frozen', 'disabled', 'theme', 'onRedeem'], variants: ['default', 'frozen'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'CalendarHeatmap', component: 'TspCalendarHeatmap', category: 'Data', description: 'Month attendance heatmap with full/partial/none/exempt levels.', props: ['yearMonth', 'cells', 'showLegend', 'theme', 'onSelectDay'], variants: ['month'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'PrintSheet', component: 'TspPrintSheet', category: 'Surfaces', description: 'A4 dictation / fill-in print layout primitive.', props: ['title', 'items', 'columns', 'footerFields', 'variant', 'theme'], variants: ['pinyin', 'meaning'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'BalanceHero', component: 'TspBalanceHero', category: 'Data', description: 'Large available-points hero with optional ledger breakdown.', props: ['total', 'breakdown', 'suffix', 'variant', 'theme'], variants: ['default', 'compact'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'CheckInStreakCard', component: 'TspCheckInStreakCard', category: 'Surfaces', description: 'Continuous check-in summary card that opens detail.', props: ['streakDays', 'totalDays', 'weekProgress', 'disabled', 'theme', 'onOpen'], variants: ['default'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },

  // W1 common controls
  { name: 'Avatar', component: 'TspAvatar', category: 'Surfaces', description: 'Circular avatar with initials or image.', props: ['text', 'src', 'size', 'variant', 'theme'], variants: ['default', 'primary', 'subtle'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'Skeleton', component: 'TspSkeleton', category: 'Feedback', description: 'Loading placeholder with optional avatar and shimmer.', props: ['rows', 'animated', 'avatar', 'variant', 'theme'], variants: ['default', 'pulse'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'Tooltip', component: 'TspTooltip', category: 'Feedback', description: 'Hover or focus tip bubble around a trigger.', props: ['text', 'placement', 'visible', 'theme', 'children'], variants: ['default'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'Slider', component: 'TspSlider', category: 'Inputs', description: 'Continuous value slider with min, max and step.', props: ['value', 'min', 'max', 'step', 'disabled', 'theme', 'onChange'], variants: ['default', 'disabled'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'TextArea', component: 'TspTextArea', category: 'Inputs', description: 'Multi-line text input with error and disabled states.', props: ['value', 'placeholder', 'rows', 'maxLength', 'disabled', 'variant', 'theme', 'onChange'], variants: ['default', 'error', 'disabled'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'Drawer', component: 'TspDrawer', category: 'Surfaces', description: 'Side or bottom overlay panel with title and close.', props: ['visible', 'title', 'placement', 'theme', 'onClose', 'children'], variants: ['default'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'InputNumber', component: 'TspInputNumber', category: 'Inputs', description: 'Numeric stepper with plus and minus controls.', props: ['value', 'min', 'max', 'step', 'disabled', 'theme', 'onChange'], variants: ['default', 'disabled'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'Swiper', component: 'TspSwiper', category: 'Navigation', description: 'Simple carousel with dots and optional autoplay.', props: ['items', 'index', 'autoplay', 'theme', 'onChange'], variants: ['default'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },

  // W2 common controls
  { name: 'Tag', component: 'TspTag', category: 'Actions', description: 'Closable or selectable status tag (distinct from Chip filter tags).', props: ['text', 'closable', 'selected', 'disabled', 'variant', 'theme', 'onClose', 'onTap'], variants: ['default', 'primary', 'success', 'warning', 'danger'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'Fab', component: 'TspFab', category: 'Actions', description: 'Floating action button, icon-only or extended with text.', props: ['icon', 'text', 'variant', 'disabled', 'theme', 'onTap'], variants: ['primary', 'default'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'TimePicker', component: 'TspTimePicker', category: 'Inputs', description: 'HH:mm time field paired with DatePicker.', props: ['value', 'placeholder', 'disabled', 'theme', 'onChange'], variants: ['default', 'disabled'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'Upload', component: 'TspUpload', category: 'Inputs', description: 'Lightweight file list and picker trigger (no upload backend).', props: ['files', 'multiple', 'disabled', 'accept', 'theme', 'onChange', 'onRemove'], variants: ['default', 'disabled'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'Table', component: 'TspTable', category: 'Data', description: 'Lightweight data table with columns, rows and striped variant.', props: ['columns', 'rows', 'variant', 'emptyText', 'theme'], variants: ['default', 'striped'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'Tree', component: 'TspTree', category: 'Data', description: 'Nested tree selector with expand and select.', props: ['items', 'selectedId', 'expandedIds', 'theme', 'onSelect', 'onExpand'], variants: ['default'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] },
  { name: 'Cascader', component: 'TspCascader', category: 'Data', description: 'Multi-level cascaded option picker.', props: ['options', 'value', 'placeholder', 'disabled', 'theme', 'onChange'], variants: ['default', 'disabled'], platforms: ['React Web', 'React Native', 'Flutter', 'iOS SwiftUI', 'Android View', 'Vue Web', 'Mini Program', 'Kuikly'] }
];
