name: tech_skill_planet_components
description: TechSkillPlanet themed Flutter basic controls with Sky Planet design language.
version: 0.2.0
repository: https://github.com/techskillplanet/planet-components
homepage: https://github.com/techskillplanet/planet-components
issue_tracker: https://github.com/techskillplanet/planet-components/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

topics:
  - ui
  - widgets
  - design-system
  - flutter

flutter:
  uses-material-design: true
